# Generated by Django 2.0.5 on 2019-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('location1', models.CharField(max_length=100)),
                ('email1', models.EmailField(max_length=100)),
                ('mobile1', models.BigIntegerField()),
                ('username1', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
    ]
